#!/usr/bin/env node
/**
 * Scan workspace packages for `"friday": { "ui": "<path>" }` and write
 * src/modules.gen.ts with an import list the shell consumes. Runs before dev,
 * build and typecheck. Fails when a declared path does not resolve or the
 * portal does not depend on the package.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export function generate(portalDir, workspaceRoot, out = join(portalDir, "src", "modules.gen.ts")) {
  const portalPkg = JSON.parse(readFileSync(join(portalDir, "package.json"), "utf8"));
  const deps = { ...portalPkg.dependencies, ...portalPkg.devDependencies };
  const ws = readFileSync(join(workspaceRoot, "pnpm-workspace.yaml"), "utf8");
  const globs = [...ws.matchAll(/^\s*-\s*["']?([^"'\n]+?)["']?\s*$/gm)].map((m) => m[1]);
  const found = [];
  for (const g of globs) {
    const [base] = g.split("/*");
    const baseDir = join(workspaceRoot, base);
    if (!existsSync(baseDir)) continue;
    const dirs = g.endsWith("/*") ? readdirSync(baseDir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => join(baseDir, d.name)) : [baseDir];
    for (const dir of dirs) {
      const pkgPath = join(dir, "package.json");
      if (!existsSync(pkgPath)) continue;
      const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
      const ui = pkg.friday?.ui;
      if (!ui) continue;
      if (!existsSync(resolve(dir, ui))) throw new Error(`${pkg.name}: friday.ui points to ${ui}, which does not exist`);
      if (!deps[pkg.name]) throw new Error(`${pkg.name} declares a portal UI but ${portalPkg.name} does not depend on it; add it to packages/portal/package.json`);
      found.push({ name: pkg.name, specifier: `${pkg.name}/ui` });
    }
  }
  found.sort((a, b) => a.name.localeCompare(b.name));
  const body =
    `// Generated by scripts/gen-modules.mjs. Do not edit; do not commit.\n` +
    `import type { ModuleUi } from "@friday/portal-ui";\n\n` +
    `export const moduleUis: Array<() => Promise<{ default: ModuleUi }>> = [\n` +
    found.map((f) => `  () => import("${f.specifier}"),`).join("\n") +
    (found.length ? "\n" : "") +
    `];\n`;
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, body);
  return found.map((f) => f.name);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const portalDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const cfg = JSON.parse(readFileSync(join(portalDir, "package.json"), "utf8")).friday ?? {};
  const names = generate(portalDir, resolve(portalDir, cfg.workspaceRoot ?? "../.."));
  console.log(`modules.gen.ts: ${names.length ? names.join(", ") : "no module UIs"}`);
}
